metadata:
  name: sko-kafka-pool
  labels:
    strimzi.io/cluster: sko-kafka-cluster
spec:
  replicas: 2
  roles:
    - broker
  storage:
    type: ephemeral
    class: longhorn
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: sko-kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.8.0.1.2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      default.replication.factor: 2
      min.insync.replicas: 2
  zookeeper:
    replicas: 2
    storage:
      type: ephemeral
  cruiseControl: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
