apiVersion: cfm.cloudera.com/v1alpha1
kind: Nifi
metadata:
  namespace: cfm-operator
  name: cloudera-nifi-demo
spec:
  replicas: 2
  image:
    repository: container.repository.cloudera.com/cloudera/cfm-nifi-k8s
    tag: 2.8.0-b94-nifi_1.25.0.2.3.13.0-36
    pullSecret: docker-pull-secret
    pullPolicy: IfNotPresent
  tiniImage:
    repository: container.repository.cloudera.com/cloudera/cfm-tini
    tag: 2.8.0-b94
    pullSecret: docker-pull-secret
    pullPolicy: IfNotPresent
  persistence:
    size: 10Gi
    storageClass: ocs-storagecluster-cephfs
    contentRepo:
      size: 50Gi
  security:
    initialAdminIdentity: cm-admin
    nodeCertGen:
      issuerRef:
        name: self-signed-ca-issuer
        kind: ClusterIssuer
  hostName: cloudera-nifi-demo.apps.field-team-ocp-01.kcloud.cloudera.com
  uiConnection:
    type: Route
    serviceConfig:
      sessionAffinity: ClientIP
    routeConfig:
      tls:
        termination: passthrough
  sensitivePropsKeySecretName: mynifi-sensitive-property-key
  configOverride:
    nifiProperties:
      upsert:
        nifi.cluster.leader.election.implementation: "KubernetesLeaderElectionManager"
    bootstrapConf:
      upsert:
        java.arg.2: -Xms2g
        java.arg.3: -Xmx2g
        java.arg.13: -XX:+UseConcMarkSweepGC
  stateManagement:
   clusterProvider:
     id: kubernetes-provider
     class: org.apache.nifi.kubernetes.state.provider.KubernetesConfigMapStateProvider
  resources:
    nifi:
      requests:
        cpu: "1"
        memory: 4Gi
      limits:
        cpu: "3"
        memory: 6Gi
    log:
      requests:
        cpu: 50m
        memory: 128Mi